# Generated by Django 5.2.5 on 2025-08-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_content_activity_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='times_completed',
            field=models.IntegerField(default=0),
        ),
    ]
