# Generated by Django 5.2.5 on 2025-09-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_activity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='last_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
