# Generated by Django 5.2.5 on 2025-09-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_activity_last_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='shared',
            field=models.BooleanField(default=False),
        ),
    ]
